export const SAVE_NAME = "SAVE_NAME";
export const SAVE_SUBNAME = "SAVE_SUBNAME";
export const SAVE_STOCK = "SAVE_STOCK";
export const SAVE_BUY_PRICE = "SAVE_BUY_PRICE";
export const SAVE_SALE_PRICE = "SAVE_SALE_PRICE";
export const SAVE_DESCRIPTION = "SAVE_DESCRIPTION";
export const SAVE_CATEGORIES = "SAVE_CATEGORIES";
export const SAVE_SUPPLIERS = "SAVE_SUPPLIERS";
