import {
	BILLS as BILLS_PATH,
	CATEGORIES as CATEGORIES_PATH,
	CONTROL_PANEL,
	PRODUCTS as PRODUCTS_PATH,
	SUPPLIERS as SUPPLIERS_PATH,
	USERS as USERS_PATH
} from "../constants/controlPanelPaths.js";

export const PRODUCTS = `${CONTROL_PANEL}/${PRODUCTS_PATH}`;
export const USERS = `${CONTROL_PANEL}/${USERS_PATH}`;
export const BILLS = `${CONTROL_PANEL}/${BILLS_PATH}`;
export const SUPPLIERS = `${CONTROL_PANEL}/${SUPPLIERS_PATH}`;
export const CATEGORIES = `${CONTROL_PANEL}/${CATEGORIES_PATH}`;
