import {
	BILLS as BILLS_PATH,
	CATEGORIES as CATEGORIES_PATH,
	CONTROL_PANEL as CONTROL_PANEL_PATH,
	PRODUCTS as PRODUCTS_PATH,
	SUPPLIERS as SUPPLIERS_PATH,
	USERS as USERS_PATH
} from "../constants/controlPanelPaths.js";

export const CONTROL_PANEL = `${CONTROL_PANEL_PATH}/`;
export const PRODUCTS = `${CONTROL_PANEL_PATH}/${PRODUCTS_PATH}`;
export const USERS = `${CONTROL_PANEL_PATH}/${USERS_PATH}`;
export const BILLS = `${CONTROL_PANEL_PATH}/${BILLS_PATH}`;
export const SUPPLIERS = `${CONTROL_PANEL_PATH}/${SUPPLIERS_PATH}`;
export const CATEGORIES = `${CONTROL_PANEL_PATH}/${CATEGORIES_PATH}`;
